测试开始了
测试报错
测试结束
2019-12-25 16:20:49,016 - root - INFO - 测试开始了 - [logger.py:25]
2019-12-25 16:20:49,016 - root - ERROR - 测试报错 - [logger.py:26]
2019-12-25 16:20:49,016 - root - INFO - 测试结束 - [logger.py:28]
2019-12-25 16:23:42,718 - case - INFO - 测试开始了 - [logger.py:25]
2019-12-25 16:23:42,719 - case - ERROR - 测试报错 - [logger.py:26]
2019-12-25 16:23:42,719 - case - INFO - 测试结束 - [logger.py:28]
2019-12-25 16:26:56,271 - case - INFO - 测试开始了 - [logger.py:28]
2019-12-25 16:26:56,271 - case - ERROR - 测试报错 - [logger.py:29]
2019-12-25 16:26:56,271 - case - INFO - 测试结束 - [logger.py:31]
